apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: service-account-token-operator
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: service-account-token-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: service-account-token-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: service-account-token-operator
    spec:
      containers:
      - command:
        - /manager
        args:
          - --metrics-bind-address=:8080
         # - --leader-elect
          - --health-probe-bind-address=:8081
        image: quay.io/orrener1337/sa-token-operator
        name: manager
        ports: []
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 800m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 128Mi
        volumeMounts: []
      volumes: []
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
