//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitLabInfo) DeepCopyInto(out *GitLabInfo) {
	*out = *in
	if in.GitLabTokenSecretRef != nil {
		in, out := &in.GitLabTokenSecretRef, &out.GitLabTokenSecretRef
		*out = new(GitLabTokenSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitLabInfo.
func (in *GitLabInfo) DeepCopy() *GitLabInfo {
	if in == nil {
		return nil
	}
	out := new(GitLabInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitLabTokenSecretRef) DeepCopyInto(out *GitLabTokenSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitLabTokenSecretRef.
func (in *GitLabTokenSecretRef) DeepCopy() *GitLabTokenSecretRef {
	if in == nil {
		return nil
	}
	out := new(GitLabTokenSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenRenewalRequest) DeepCopyInto(out *TokenRenewalRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenRenewalRequest.
func (in *TokenRenewalRequest) DeepCopy() *TokenRenewalRequest {
	if in == nil {
		return nil
	}
	out := new(TokenRenewalRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TokenRenewalRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenRenewalRequestList) DeepCopyInto(out *TokenRenewalRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TokenRenewalRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenRenewalRequestList.
func (in *TokenRenewalRequestList) DeepCopy() *TokenRenewalRequestList {
	if in == nil {
		return nil
	}
	out := new(TokenRenewalRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TokenRenewalRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenRenewalRequestSpec) DeepCopyInto(out *TokenRenewalRequestSpec) {
	*out = *in
	out.RenewalAfter = in.RenewalAfter
	if in.GitLabInfo != nil {
		in, out := &in.GitLabInfo, &out.GitLabInfo
		*out = new(GitLabInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenRenewalRequestSpec.
func (in *TokenRenewalRequestSpec) DeepCopy() *TokenRenewalRequestSpec {
	if in == nil {
		return nil
	}
	out := new(TokenRenewalRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenRenewalRequestStatus) DeepCopyInto(out *TokenRenewalRequestStatus) {
	*out = *in
	if in.LastRenewalTime != nil {
		in, out := &in.LastRenewalTime, &out.LastRenewalTime
		*out = (*in).DeepCopy()
	}
	if in.TokenExpirationTime != nil {
		in, out := &in.TokenExpirationTime, &out.TokenExpirationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenRenewalRequestStatus.
func (in *TokenRenewalRequestStatus) DeepCopy() *TokenRenewalRequestStatus {
	if in == nil {
		return nil
	}
	out := new(TokenRenewalRequestStatus)
	in.DeepCopyInto(out)
	return out
}
