---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - or.io.or.io
  resources:
  - tokenrenewalrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - or.io.or.io
  resources:
  - tokenrenewalrequests/finalizers
  verbs:
  - update
- apiGroups:
  - or.io.or.io
  resources:
  - tokenrenewalrequests/status
  verbs:
  - get
  - patch
  - update
